language: scala

scala:
  - 2.13.1
  - 2.12.10

jdk: openjdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier/cache

env:
  global:
    - COURSIER_PROGRESS=0
    - SBT=./sbt
    # ENCRYPTION_PASSWORD
    - secure: "A4h/cwE0RTs4YwOm3Jh9qS77z+Q+beErAviaaRH9egqDsuR+YjsRVJ0gDwkFIUW22UPW6geghS+SUEZ39Ok40vFR48d08Eq70WrVdBcixl0S8tGs2aDTNp/opoWJtaF7Nf4YpMkxw2+iddSIQSEu2RRS/FehMmb8yyP0a4oqxYTu6gKa51ElCO8YXCchL3+atKuk8tMy6uknLT+yeaF0f/ytHyHofRvuYCT4KYGJP2TwHO4O5gPOT1cEcnEBW9HXSdg4sqVcy/9aiosdHeOvLlI6zOK0wd968J+3Ve3nGq1nK9WFsRNwZD8Af3T7ZNYkqiC9+NEao8ELJOvHvj6UbkwEuOFNhI9/W2YFk7asbAwszyZQ/2E4adAuO5ly5yJ37kRHaiZzkThkOTUr3BmOh4GIXncOccy1YZsWee2JGt9UhBumj0lLspXUFRrscc2QfU6IVq34+gZPKBPMCRCpL+HXoT225x2HtDCuVk4c+te3syQcb716IqM6uBvm3dIAQtgHy1dPfeU78Puu/zxaKFKldVq4IbAGCat+d6M6AA7AsQWn/vI315avF6OOk7KGnrwRXgV2ZZjVTHnC24k+Bg7p/sLBeQMEEeWeBZoR1Ijkz9ubGTfdUY00ACzr32kKc8MNjjr1luigRl+JuZglpSHpsgxj1rFruSC3/AoM1oo="
    # GITHUB_TOKEN
    - secure: "r0ohoB9ZbBThD+4+4IkVTM8fPEcAbllidnPQq2/Nz5G3kVGdmzR0taimnJFPOHnam/xogqnfKrlRGbipugRY9M7Gq2OETm4FnTmrljzpOPa3Z4oOLdedYKInUis1nBMYgYrabjAo/XtK7d4i+vVW8e47ciMxlpLCqJ3z0ftlXvWDEwyN3/ykolBveD5FTaqQgFSA6nri5ARF8Uv2ykute/0nDddAvhyZ0S8A43bDZBphrgNCC2JP6CKINZ7fFsVUlkx5poFXYHQaIhyZUptij4zrXYVazSOIfNYk1B2FrF2eZzY+O6AeDkPvUiq90cM5VQgkZk8MnMZ73+f/DNQkuitAu1zvqJ89omApAz+OHJ1VCKb7MZJfimtf+4O74KBigmaKI9AtMnHQ96cUNIe4YPv0yIDv/eKWAYJwFdCIYSNTQ3oqMWDuvFP446CA+92gHyr4W/pe8Y46FwmhAaV0881SPBNY9RvMrBTNy54BqI0tioz8bwcs+UzNZC/SF+bkbzjipN9mqDPt7AeNjtSO60QizAuFPJHHgn3FQfakNPJUk24FDvkq2hdNIXH99J2hHGjo3OBoXXMVcwgHSS6z4s58+0sPXNh/0kke+KhMFo7GJ8eUG3J0PKfQa4E61osiqQT4JkAccHFhcaDoqLkSaR9dF4jGqaGK/L2D/u22TmE="
    # GITHUB_ACCESS_TOKEN
    - secure: "epxgQczxQlcxMnPQGy/nlK8r49oC0SitwY3Pby8kdGC9qIMi/zy/oFs7jwLreBCB36yl9jwneneEoKRH1i0++R1xo5pzUY2ch2N2SBZ8WUMrg3I0nlhOl4WJbOGRtEaw/9mCEZPRD/VqUtg5Dl3MnvsA7uapF18t1f3/+UgHKaYEWXUG+LZtZdEivHnBmBNgLznvTw86UyEvAM9Zt2FlLwnTs/FeE6pugLivP96p4Zxu70Tgnx9NyuFcjx+N7X77Y54nDWRcYjTgttLs25OxbaKrXbnB0IIq2fM34ESJq5rUVHhamBzsBY1gdgFuouJaGktUYTbE2PRi8GEiercGF8NcaOhPeG4l7m+DPtbZ3AA5UyYR2BWi0bGCpac708zislKQLs0tZa6nZRjI9tkhbxHhUCPFNAUsmDLQfvHug6lT5gFawcLPc76g3JkOb4I/XXUqjhYJluLTB9/6afvnak60tYf3Xjua6vGm1GjnoE5LwXQu8e0eRxShjvUnV4PZIU4eGhsS2ugPeWw+wTVGva5K71Bhdihb1q0LA0Jz1lp8mCU0Tt5v/yV1cKVD3RqwEUZGpvbqAAVJZYOBevay9ro4Vn6dmuHyjLQSfpBueo6acRzORfzOUpd+gG4a27QVp5pOGeFNwl/LQ8oTkxTUlFEYd5lsJRr14JEpEUM9nmk="
    # DISCORD_WEBHOOK_TOKENS
    - secure: "rtBN4Gv2ztG2y6xV0tSlk9jvjJLkd4xNYdvq5xt25aE8xOywu1V1zHv0t+gXmg8UNjrLktzM3NQUl7g2Ix8BE4i3fc7yJSf05j5GMwG5NhCm9fiyJh4z4TMCTU+2rn/LzvoH057jH2TVL9DajecRk8gdtA9Htdn5UFvQbdsrprKa9SulxiXq9e1cnDu6NjfFMYWaVqavmvc7ZAErgWmwNRW0ztkrsPQ6k//MYprJhDnBLVmrSm8veKnaFpgXDGqvxb68Ouev0lWxE7gY9vj4Ng2hAqrhI/+6XEja3Gzz9tMdCZPpFs6LqAwo3AgU2+OlsnPxtQOi14QnrL4RftaIg504aE+1xMAr8naam86J2JgDXqbl0+r6qqFfaaiP73osrMjXRoQPdISKcTBRPUHcNDyIavtX63dt52XVSjlSgIMwDfdOYNpB4K+BbRvx0TNPlKvVm43Nt5IUqrIwT8Eam73RYyjW5BQrdnUSm5IW4mkid4kZ3ASb9Vy8Drx++F5P60nap06X0ncI5MHqqhROxuDq9m1KT9RybE5rTZin1NiR4uCz/Xhpz02dmKzhYD4D+YbvwjRY1skH+/XCTS98AFJmkzTp0EuX64DtDswgUP3Fepif6e0yz5EShBxHPKrIJkdszFdV3fIEr4BZcSoGsDL/QgWpyEKiwhOOYd0p8hA="

install:
  - mkdir scripts
  - $SBT transferCommonResources
  - scripts/commonSetup

script:
    - set -e

    - $SBT ++$TRAVIS_SCALA_VERSION test

    - |-
      if [[ $TRAVIS_SCALA_VERSION =~ 2.12 ]]; then
        if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ "$TRAVIS_BRANCH" =~ backport/v.*|master ]]; then
          $SBT transferPublishAndTagResources
          TRAVIS_JOB_NUMBER=1 scripts/publishAndTag 'slamdata/http4s-client-oauth'
        fi

        scripts/checkAndAutoMerge
      fi

after_success: scripts/discordTravisPost success https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

after_failure: scripts/discordTravisPost failure https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

branches:
  only:
    - master
    - /^backport.*$/
